In [2]:
import pandas as pd
from sklearn.feature_extraction import text
stop = text.ENGLISH_STOP_WORDS
import enchant
from collections import Counter
import warnings
warnings.filterwarnings('ignore')
d = enchant.Dict("en_US")
words = pd.read_csv('words.csv', index_col=0)

In [3]:

freqdf = pd.DataFrame(columns=["Year", "Frequency", "Country", "Document"])
for row in range(words.__len__()):
    r = words.loc[row]
    w = r["Words"]
    w = w.replace("'", '').replace("[", '').replace("]", '').replace(",", '').split()
    rw = []
    for i in w:
        if d.check(i) and len(i) > 1 and i.lower() not in stop and i.isalpha():
            rw.append(i)
    counts = Counter(rw)
    freqdf = freqdf.append({"Year":r["Year"], "Frequency":counts.most_common(20), "Country":r["Country"], "Document":r["Document"]}, ignore_index=True)
    print(f"{row}/{words.__len__()}", end="\r")

In [19]:
freqdf.to_csv("freqdf.csv")

,Year,Words,Country,Document
0,2008,"['of', 'DOCUMENTS', 'Reed', 'International', '...",AUSTRALIA,20080502_2008-NSWSC-244-Australia_opinion
1,2008,"['FCA', 'FOR', 'EDUCATIONAL', 'USE', 'ONLY', '...",AUSTRALIA,20080918_2008-FCA-1428_opinion-1
2,2010,"['VCAT', 'FOR', 'EDUCATIONAL', 'USE', 'ONLY', ...",AUSTRALIA,20100421_2010-VCAT-480_decision
3,2010,"['FEDERAL', 'COURT', 'OF', 'AUSTRALIAAustralia...",AUSTRALIA,20100929_2010-FCA-1057_opinion-1
4,2015,"['BarNet', 'publication', 'information', '-', ...",AUSTRALIA,20150715_2015-FCA-785-325-ALR-736-1_decision-1
...,...,...,...,...
9933,2023,"['No.', '-', 'IN', 'THE', 'United', 'States', ...",USA,20230612_docket-21-16278_amicus-brief-6
9934,2023,"['Case', 'No.', '-', 'IN', 'THE', 'UNITED', 'S...",USA,20230612_docket-21-16278_amicus-brief-7
9935,2023,"['Case', 'No.', '-', 'IN', 'THE', 'UNITED', 'S...",USA,20230612_docket-21-16278_amicus-brief-8
9936,2023,"['No.', '-', 'IN', 'THE', 'UNITED', 'STATES', ...",USA,20230612_docket-21-16278_amicus-brief
9937,2023,"['Melissa', 'Powers', 'Carra', 'Sahler', 'S.',...",USA,20230612_docket-21-16278_letter

In [21]:
groupedwordsdf = words.groupby(["Year", "Country"]).sum()

In [26]:
groupedwordsdf.reset_index(inplace=True)
groupedwordsdf

,index,Year,Country,Words,Document
0,0,1970,USA,"['IN', 'THE', 'UNITED', 'STATES', 'DISTRICT', ...",19700126_docket-14-cv-01471_motion-for-summary...
1,1,1990,USA,"['U.S.', 'App.', 'D.C.', 'F.', 'd', 'U.S.', 'A...",19900824_docket-86-1649-86-1651-86-1652-89-127...
2,2,1992,USA,"['F.', 'Supp.', 'U.S.', 'Dist.', 'LEXIS', 'ELR...",19920429_docket-89-1483_memorandum-opinion-1
3,3,1994,USA,"['F.', 'Supp.', 'U.S.', 'Dist.', 'LEXIS', 'ELR...",19941221_docket-C92-479WD-C94-758WD-C94-803WD-...
4,4,1997,USA,"['F.', 'd', 'U.S.', 'App.', 'LEXIS', 'Cal.', '...",19970924_docket-95-70862-95-70927-95-70928-95-...
...,...,...,...,...,...
71,71,2022,USA,"['No.', '-', '-', 'IN', 'THE', 'UNITED', 'STAT...",20220103_docket-20-70272_petition-for-rehearin...
72,72,2023,FRANCE,"['This', 'is', 'an', 'unofficial', 'machine', ...",20230223_18777_summons-1
73,73,2023,PENDING,"['T', 'E', 'sydney', 'edo.org.au', 'F', 'W', '...",20230302_19330_complaint
74,74,2023,UK,"['You', 'Should', 'Feel', 'Guilty', 'for', 'No...",20230216_19113_press-release20230217_19113_na
75,75,2023,USA,"['No.', '-', 'In', 'the', 'Supreme', 'Court', ...",20230103_docket-22-361_reply20230104_docket-12...

In [35]:
groupedfreqdf = pd.DataFrame(columns=["Year", "Frequency", "Country", "Document"])
for row in range(groupedwordsdf.__len__()):
    r = groupedwordsdf.loc[row]
    w = r["Words"]
    w = w.replace("'", '').replace("[", '').replace("]", '').replace(",", '').split()
    rw = []
    for i in w:
        i = i.lower()
        if d.check(i) and len(i) > 1 and i not in stop and i.isalpha():
            rw.append(i)
    counts = Counter(rw)
    groupedfreqdf = groupedfreqdf.append({"Year":r["Year"], "Frequency":counts.most_common(20), "Country":r["Country"], "Document":r["Document"]}, ignore_index=True)
    print(f"{row}/{groupedwordsdf.__len__()}", end="\r")

In [36]:
groupedfreqdf.drop(groupedfreqdf.index[groupedfreqdf['Country'] == "PENDING"], inplace = True)
groupedfreqdf.to_csv("groupedfreqdf.csv")